// <auto-generated />
using System;
using Davetiye.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Davetiye.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DavetiyeDbContext))]
    [Migration("20261004155857_P4M4_MediaVerification")]
    partial class P4M4_MediaVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Davetiye.Domain.Modules.Analytics.InvitationViewTotal", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<long>("Total")
                        .HasColumnType("bigint")
                        .HasColumnName("total");

                    b.HasKey("InvitationId")
                        .HasName("pk_invitation_view_totals");

                    b.ToTable("invitation_view_totals", null, t =>
                        {
                            t.HasCheckConstraint("ck_invitation_view_totals_nonnegative", "total >= 0");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.IdentityAndAccounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_identity_user_id");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.IdentityAndAccounts.BanRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<Guid>("BannedByActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("banned_by_actor_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id")
                        .HasName("pk_ban_records");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_ban_records_account_id");

                    b.ToTable("ban_records");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.IntegrationFoundation.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until");

                    b.Property<bool>("FailedPermanently")
                        .HasColumnType("boolean")
                        .HasColumnName("failed_permanently");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_event_id");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_name");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.HasIndex("ProviderName", "ProviderEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_inbox_messages_provider_name_provider_event_id");

                    b.HasIndex("ProcessedAt", "FailedPermanently", "NextAttemptAt")
                        .HasDatabaseName("ix_inbox_messages_processed_at_failed_permanently_next_attempt~");

                    b.ToTable("inbox_messages");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.IntegrationFoundation.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset?>("ClaimedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FailedPermanently")
                        .HasColumnType("boolean")
                        .HasColumnName("failed_permanently");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAt", "FailedPermanently", "NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_failed_permanently_next_attemp~");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Invitations.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("public_code")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("PurgeAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_after");

                    b.Property<int?>("RendererVersion")
                        .HasColumnType("integer")
                        .HasColumnName("renderer_version");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<string>("TemplateKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_invitations_account_id");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("ux_invitations_public_code");

                    b.ToTable("invitations", t =>
                        {
                            t.HasCheckConstraint("ck_invitations_public_code_format", "public_code ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_invitations_state_supported", "state IN ('Draft', 'Scheduled', 'Active', 'Paused', 'Expired')");

                            t.HasCheckConstraint("ck_invitations_template_pin_pairing", "(template_key IS NULL) = (renderer_version IS NULL)");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Invitations.PublicationWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("grant_id");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("Id")
                        .HasName("pk_publication_windows");

                    b.HasIndex("GrantId")
                        .HasDatabaseName("ix_publication_windows_grant_id");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("ux_publication_windows_current_invitation")
                        .HasFilter("is_current");

                    b.HasIndex("IsCurrent", "StartsAt", "EndsAt")
                        .HasDatabaseName("ix_publication_windows_current_interval");

                    b.ToTable("publication_windows", t =>
                        {
                            t.HasCheckConstraint("ck_publication_windows_interval", "starts_at < ends_at");

                            t.HasCheckConstraint("ck_publication_windows_timezone_not_blank", "length(btrim(time_zone_id)) > 0");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Invitations.PublishedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<int>("ContentSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("content_schema_version");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RendererVersion")
                        .HasColumnType("integer")
                        .HasColumnName("renderer_version");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<long>("SourceWorkingRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_working_revision");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_published_contents");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("ix_published_contents_invitation_id");

                    b.ToTable("published_contents", t =>
                        {
                            t.HasCheckConstraint("ck_published_contents_renderer_version_positive", "renderer_version > 0");

                            t.HasCheckConstraint("ck_published_contents_schema_version_positive", "content_schema_version > 0");

                            t.HasCheckConstraint("ck_published_contents_source_revision_non_negative", "source_working_revision >= 0");

                            t.HasCheckConstraint("ck_published_contents_update_order", "updated_at >= published_at");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Invitations.WorkingContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<int>("ContentSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("content_schema_version");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_working_contents");

                    b.HasIndex("InvitationId")
                        .IsUnique()
                        .HasDatabaseName("ix_working_contents_invitation_id");

                    b.ToTable("working_contents");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Media.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("DetectedContentType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("detected_content_type");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ProviderDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("provider_deleted_at");

                    b.Property<string>("ProviderObjectReference")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_object_reference");

                    b.Property<string>("QuotaScope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quota_scope");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_media_assets");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("ix_media_assets_state_created_at");

                    b.HasIndex("InvitationId", "QuotaScope", "Kind", "State")
                        .HasDatabaseName("ix_media_assets_invitation_quota_kind_state");

                    b.ToTable("media_assets", t =>
                        {
                            t.HasCheckConstraint("ck_media_assets_deleted_timestamp", "state <> 'Deleted' OR provider_deleted_at IS NOT NULL");

                            t.HasCheckConstraint("ck_media_assets_deletion_timestamps", "state NOT IN ('PendingDeletion', 'Deleted') OR deletion_requested_at IS NOT NULL");

                            t.HasCheckConstraint("ck_media_assets_positive_measurements", "(byte_length IS NULL OR byte_length > 0) AND (duration_seconds IS NULL OR duration_seconds > 0)");

                            t.HasCheckConstraint("ck_media_assets_ready_metadata", "state <> 'Ready' OR (provider_object_reference IS NOT NULL AND detected_content_type IS NOT NULL AND byte_length > 0 AND ready_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_media_assets_supported_values", "quota_scope IN ('Creator', 'Guest') AND kind IN ('Image', 'Video') AND state IN ('PendingUpload', 'Processing', 'Ready', 'Rejected', 'PendingDeletion', 'Deleted')");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Media.MediaPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_media_placements");

                    b.HasIndex("MediaAssetId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ux_media_placements_asset_role");

                    b.HasIndex("Role", "SortOrder")
                        .HasDatabaseName("ix_media_placements_role_sort_order");

                    b.ToTable("media_placements", t =>
                        {
                            t.HasCheckConstraint("ck_media_placements_nonnegative_sort_order", "sort_order >= 0");

                            t.HasCheckConstraint("ck_media_placements_supported_role", "role IN ('Cover', 'Gallery')");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Media.MediaProviderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_fingerprint");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.HasKey("Id")
                        .HasName("pk_media_provider_events");

                    b.HasIndex("EventFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_media_provider_events_event_fingerprint");

                    b.ToTable("media_provider_events", t =>
                        {
                            t.HasCheckConstraint("ck_media_provider_events_fingerprint", "length(event_fingerprint) = 64");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Media.PendingUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("DeclaredByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("declared_byte_length");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uuid")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("MaximumByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("maximum_byte_length");

                    b.Property<long>("MaximumDurationSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("maximum_duration_seconds");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_fingerprint");

                    b.Property<string>("RequestedPresentationRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("requested_presentation_role");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_pending_uploads");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_pending_uploads_idempotency_key");

                    b.HasIndex("MediaAssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_pending_uploads_one_open_per_asset")
                        .HasFilter("consumed_at IS NULL AND cancelled_at IS NULL");

                    b.HasIndex("ConsumedAt", "CancelledAt", "ExpiresAt")
                        .HasDatabaseName("ix_pending_uploads_open_expiry");

                    b.ToTable("pending_uploads", t =>
                        {
                            t.HasCheckConstraint("ck_pending_uploads_expiry_after_creation", "created_at < expires_at");

                            t.HasCheckConstraint("ck_pending_uploads_request_values", "declared_byte_length > 0 AND maximum_byte_length >= declared_byte_length AND maximum_duration_seconds >= 0 AND length(request_fingerprint) = 64 AND requested_presentation_role IN ('Cover', 'Gallery')");

                            t.HasCheckConstraint("ck_pending_uploads_terminal_state_pairing", "consumed_at IS NULL OR cancelled_at IS NULL");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.PlansAndEntitlements.AccountPlanGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid?>("AssignedInvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_invitation_id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset?>("ReservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reserved_at");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_account_plan_grants");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_account_plan_grants_lifetime_free_per_account")
                        .HasFilter("source = 'Free'");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_account_plan_grants_plan_id");

                    b.HasIndex("AccountId", "RevokedAt", "ConsumedAt")
                        .HasDatabaseName("ix_account_plan_grants_account_id_revoked_at_consumed_at");

                    b.ToTable("account_plan_grants", t =>
                        {
                            t.HasCheckConstraint("ck_account_plan_grants_consumption_order", "consumed_at IS NULL OR consumed_at >= reserved_at");

                            t.HasCheckConstraint("ck_account_plan_grants_consumption_requires_reservation", "consumed_at IS NULL OR reserved_at IS NOT NULL");

                            t.HasCheckConstraint("ck_account_plan_grants_reservation_pairing", "(assigned_invitation_id IS NULL) = (reserved_at IS NULL)");

                            t.HasCheckConstraint("ck_account_plan_grants_shared_grant_unassigned", "source <> 'OrganizationSubscription' OR (assigned_invitation_id IS NULL AND reserved_at IS NULL AND consumed_at IS NULL)");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.PlansAndEntitlements.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("billing_kind");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key");

                    b.Property<decimal>("PriceAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("price_amount");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_key");

                    b.ToTable("plans", t =>
                        {
                            t.HasCheckConstraint("ck_plans_billing_kind_supported", "billing_kind IN ('Free', 'OneTime', 'Monthly')");

                            t.HasCheckConstraint("ck_plans_currency_iso_length", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_plans_free_price", "billing_kind <> 'Free' OR price_amount = 0");

                            t.HasCheckConstraint("ck_plans_price_non_negative", "price_amount >= 0");
                        });
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.PlansAndEntitlements.PlanEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("boolean_value");

                    b.Property<string>("EntitlementKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entitlement_key");

                    b.Property<long?>("NumericValue")
                        .HasColumnType("bigint")
                        .HasColumnName("numeric_value");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_plan_entitlements");

                    b.HasIndex("PlanId", "EntitlementKey")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_entitlements_plan_id_entitlement_key");

                    b.ToTable("plan_entitlements");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.PlansAndEntitlements.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("value_type");

                    b.HasKey("Id")
                        .HasName("pk_system_settings");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_system_settings_key");

                    b.ToTable("system_settings");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Templates.TemplateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<int>("CurrentRendererVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_renderer_version");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PreviewImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preview_image_url");

                    b.Property<string>("RecommendedFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_fields");

                    b.Property<string>("RequiredFields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_fields");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("SupportedModules")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("supported_modules");

                    b.HasKey("Id")
                        .HasName("pk_template_definitions");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_template_definitions_is_active");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_template_definitions_key");

                    b.ToTable("template_definitions");
                });

            modelBuilder.Entity("Davetiye.Infrastructure.Modules.IdentityAndAccounts.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("email_index");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("user_name_index");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Analytics.InvitationViewTotal", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.Invitations.Invitation", null)
                        .WithOne()
                        .HasForeignKey("Davetiye.Domain.Modules.Analytics.InvitationViewTotal", "InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_view_totals__invitations_invitation_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.IdentityAndAccounts.Account", b =>
                {
                    b.HasOne("Davetiye.Infrastructure.Modules.IdentityAndAccounts.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("Davetiye.Domain.Modules.IdentityAndAccounts.Account", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts__asp_net_users_identity_user_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.IdentityAndAccounts.BanRecord", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.IdentityAndAccounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ban_records_accounts_account_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Invitations.PublicationWindow", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.Invitations.Invitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_publication_windows_invitations_invitation_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Invitations.PublishedContent", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.Invitations.Invitation", null)
                        .WithOne()
                        .HasForeignKey("Davetiye.Domain.Modules.Invitations.PublishedContent", "InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_published_contents_invitations_invitation_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Invitations.WorkingContent", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.Invitations.Invitation", null)
                        .WithOne()
                        .HasForeignKey("Davetiye.Domain.Modules.Invitations.WorkingContent", "InvitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_working_contents_invitations_invitation_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Media.MediaAsset", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.Invitations.Invitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_media_assets_invitations_invitation_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Media.MediaPlacement", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.Media.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_placements_media_assets_media_asset_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.Media.PendingUpload", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.Media.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pending_uploads_media_assets_media_asset_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.PlansAndEntitlements.AccountPlanGrant", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.PlansAndEntitlements.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_plan_grants__plans_plan_id");
                });

            modelBuilder.Entity("Davetiye.Domain.Modules.PlansAndEntitlements.PlanEntitlement", b =>
                {
                    b.HasOne("Davetiye.Domain.Modules.PlansAndEntitlements.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_plan_entitlements_plans_plan_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Davetiye.Infrastructure.Modules.IdentityAndAccounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Davetiye.Infrastructure.Modules.IdentityAndAccounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Davetiye.Infrastructure.Modules.IdentityAndAccounts.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
