/**
 * Super Admin page copy. Merge `adminUiTranslations.tr.adminUi` and
 * `adminUiTranslations.en.adminUi` into the corresponding `translation.adminUi`
 * entries in i18n/index.ts. Components use the default namespace with keys
 * such as `t('adminUi.banned.title')`; Turkish remains the app default.
 */
export const adminUiTranslations = {
  tr: {
    adminUi: {
      banned: {
        title: 'Banlı hesaplar', description: 'Banlı hesap özetlerini e-posta başlangıcına göre arayın. Dahili notlar burada gösterilmez.', total: 'Toplam: {{count}}', emailPrefix: 'E-posta başlangıcı', search: 'Ara', loading: 'Banlı hesaplar yükleniyor…', loadFailed: 'Banlı hesaplar yüklenemedi', retry: 'Yeniden dene', emptyMatchTitle: 'Eşleşen banlı hesap yok', emptyTitle: 'Banlı hesap yok', tryDifferentPrefix: 'Farklı bir e-posta başlangıcı deneyin.', emptyBody: 'Banlı hesaplar bu listede görünür.', pages: 'Banlı hesaplar sayfaları', previous: 'Önceki', next: 'Sonraki', page: 'Sayfa {{current}} / {{total}}', caption: 'Banlı hesaplar', account: 'Hesap', email: 'E-posta', type: 'Tür', created: 'Kayıt tarihi', bannedAt: 'Ban tarihi', reason: 'Sebep', action: 'İşlem', unnamedAccount: 'İsimsiz hesap', noEmail: 'E-posta yok', unspecified: 'Belirtilmedi', unban: 'Banı kaldır', unbanning: 'Ban kaldırılıyor…', unbanAria: '{{name}} hesabının banını kaldır', individual: 'Bireysel', organization: 'Organizasyon', authRequired: 'Bu görünüm için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', loadError: 'Banlı hesaplar şu anda alınamadı. Biraz sonra yeniden deneyin.', confirmUnban: '{{name}} hesabının banını kaldırmak istiyor musunuz? Hesabın erişimi geri gelir.', unbanSuccess: '{{name}} hesabının banı kaldırıldı.', actionAuthRequired: 'İşlem için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', unbanError: 'Ban kaldırılamadı. Hesap durumu değişmiş olabilir; listeyi yenileyip tekrar deneyin.',
      },
      plans: {
        title: 'Planlar ve haklar', description: 'Plan adını, açıklamasını, fiyatı, faturalandırma türünü ve desteklenen hak değerlerini yönetin.', loading: 'Planlar yükleniyor…', loadFailed: 'Planlar yüklenemedi', loadError: 'Plan listesi şu anda alınamadı. Biraz sonra yeniden deneyin.', retry: 'Yeniden dene', emptyTitle: 'Yönetilecek plan yok', emptyBody: 'Plan tanımları eklendiğinde burada görünür.', planList: 'Düzenlenecek plan', planDetails: 'Plan bilgileri', revision: 'Sürüm {{revision}}', planName: 'Plan adı', descriptionLabel: 'Açıklama', optional: '(isteğe bağlı)', maxChars: 'En çok 2.000 karakter.', amount: 'Plan tutarı ({{currency}})', priceHint: 'En fazla 4 ondalık basamak. Ücretsiz planın tutarı 0; tek seferlik ve aylık planların tutarı 0’dan büyük olmalıdır. Para birimi salt okunurdur. Fiyat değişikliği yalnızca yeni alımlara uygulanır; mevcut yayın hakları ve abonelikler eski fiyatını korur.', billing: 'Faturalandırma türü', free: 'Ücretsiz', oneTime: 'Tek seferlik', periodMonthly: 'aylık', periodOneTime: 'tek sefer', periodFree: 'ücretsiz', monthly: 'Aylık', freeMustBeZero: 'Ücretsiz planın tutarı sıfır olmalıdır. Tutarı 0 yapın veya başka bir faturalandırma türü seçin.', paidMustBePositive: 'Ücretli planların tutarı sıfırdan büyük olmalıdır. Pozitif bir tutar girin.', entitlements: 'Plan hakları', entitlementHint: 'Sayısal alanlar tam sayı kabul eder. Desteklenen üst sınırlar sunucuda doğrulanır; buradaki değerler mevcut kullanım verisini silmez.', missingEntitlement: 'Could not load data for {{name}}.', enabled: 'Açık', disabled: 'Kapalı', currentRevision: 'Güncel plan sürümü', refreshConflict: 'Sunucudaki güncel değerleri yükleyin. Yerel düzenlemeler bu işlem yapılana kadar korunur.', refresh: 'Güncel sürümü yükle', saveChanges: 'Değişiklikleri kaydet', saving: 'Kaydediliyor…', visible: 'katalogda görünür', hidden: 'katalogda gizli', confirmSave: '“{{name}}” planı {{oldPrice}} → {{newPrice}} olarak güncellenecek. Fiyat ve faturalandırma değişikliği yalnızca yeni alımlara uygulanır; mevcut yayın hakları ve aboneliklerin fiyatı korunur. Hak limitleri düşerse mevcut veriler silinmez. Devam edilsin mi?', saved: '{{name}} planı kaydedildi.', stale: 'Plan siz düzenlerken başka bir yönetici tarafından değiştirildi. Yerel düzenlemeleriniz korunuyor; kaydetmeden önce güncel sürümü yükleyin.', invalidServer: 'Sunucu plan değerlerini veya desteklenen sınırları kabul etmedi. Değerleri gözden geçirip yeniden deneyin.', authRequired: 'Bu görünüm için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', saveAuthRequired: 'Kaydetmek için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', saveError: 'Plan kaydedilemedi. Bağlantınızı kontrol edip yeniden deneyin.',
        fields: { maxPublishDays: 'En uzun yayın süresi (gün)', maxActiveInvitations: 'Aynı anda aktif davetiye', maxImages: 'Creator fotoğraf kotası', maxVideos: 'Creator video kotası', maxImageSizeMb: 'Creator fotoğraf boyutu (MB)', maxVideoSizeMb: 'Creator video boyutu (MB)', maxVideoDurationSeconds: 'Creator video süresi (saniye)', maxGuestImages: 'Misafir fotoğraf kotası', maxGuestVideos: 'Misafir video kotası', maxGuestImageSizeMb: 'Misafir fotoğraf boyutu (MB)', maxGuestVideoSizeMb: 'Misafir video boyutu (MB)', maxGuestVideoDurationSeconds: 'Misafir video süresi (saniye)', maxRSVPResponses: 'Davetiye başına RSVP yanıtı', memoriesEnabled: 'Anı modülü', giftRegistryEnabled: 'Hediye listesi', premiumTemplatesEnabled: 'Premium şablonlar' },
      },
      settings: {
        title: 'Sistem ayarları', description: 'Yalnızca davetiye ve tamamlanmamış anı saklama süreleri düzenlenebilir.', loading: 'Sistem ayarları yükleniyor…', loadFailed: 'Ayarlar yüklenemedi', loadError: 'Sistem ayarları şu anda alınamadı. Biraz sonra yeniden deneyin.', retry: 'Yeniden dene', emptyTitle: 'Düzenlenebilir saklama ayarı yok', emptyBody: 'Onaylı saklama ayarları API tarafından sağlandığında burada görünür.', days: 'Süre (gün)', range: '0–365 tam gün. Sunucu sınırı: {{minimum}}–{{maximum}} gün.', currentValue: '{{name}} güncel değeri', unsavedPreserved: 'Kaydedilmemiş değeriniz korunuyor. Güncel sunucu değerini yüklediğinizde düzenlemeniz değiştirilir.', refresh: 'Güncel değeri yükle', saving: 'Kaydediliyor…', save: 'Değişikliği kaydet', revision: 'Sürüm {{revision}}', authRequired: 'Bu ayarları görmek için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', refreshError: 'Güncel ayar alınamadı. Bağlantınızı kontrol edip yeniden deneyin.', invalidDays: 'Saklama süresi 0 ile 365 arasında tam gün olmalıdır.', confirmSave: '{{name}} ayarını {{value}} gün olarak kaydetmek istiyor musunuz? {{impact}}', saved: '{{name}} kaydedildi. Yeni alımlarda ve ilgili yeni kayıt işlemlerinde geçerli olur.', conflict: '{{name}} siz düzenlerken başka bir yönetici tarafından değiştirildi. Değişikliğiniz korunuyor; kaydetmeden önce güncel değeri yükleyin.', saveAuthRequired: 'Kaydetmek için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', saveError: 'Ayar kaydedilemedi. Değeri kontrol edip yeniden deneyin.', settingTitles: { deletedInvitationRetentionDays: 'Silinen davetiyelerin saklama süresi', abandonedMemoryRetentionDays: 'Tamamlanmamış anı kayıtlarının saklama süresi' }, settingEffects: { deletedInvitationRetentionDays: 'Bu değişiklik, bundan sonra çöp kutusuna taşınan davetiyelere uygulanır. Mevcut davetiyelerin kalıcı silinme tarihleri değişmez.', abandonedMemoryRetentionDays: 'Süresi dolan Abandoned anı ve capability metadata kayıtları sınırlı partilerle temizlenir. MediaAsset, PendingUpload, sağlayıcı dosya baytları ve misafir kotası davetiye kalıcı silinene kadar korunur.' },
      },
      templates: {
        title: 'Şablonlar', description: 'Şablon adını, isteğe bağlı açıklamasını ve katalog görünürlüğünü yönetin. Tasarım ve renderer bilgileri kod tarafından yönetilir.', loading: 'Şablonlar yükleniyor…', loadFailed: 'Şablonlar yüklenemedi', loadError: 'Şablon listesi şu anda alınamadı. Biraz sonra yeniden deneyin.', retry: 'Yeniden dene', emptyTitle: 'Yönetilecek şablon yok', emptyBody: 'Şablon tanımları eklendiğinde burada görünür.', listLabel: 'Düzenlenecek şablon', visible: 'Görünür', hidden: 'Gizli', details: 'Şablon bilgileri', revision: 'Sürüm {{revision}}', name: 'Ad', descriptionLabel: 'Açıklama', optional: '(isteğe bağlı)', maxChars: 'En çok 2.000 karakter.', showInCatalog: 'Katalogda göster', hiddenHint: 'Gizlenen şablon yeni seçimlerden kaldırılır; mevcut taslak ve yayınlar etkilenmez.', currentRevision: 'Güncel şablon sürümü', refreshConflict: 'Sunucudaki güncel değerleri yükleyerek bu değişiklikleri yenileyin.', refresh: 'Güncel sürümü yükle', saveChanges: 'Değişiklikleri kaydet', saving: 'Kaydediliyor…', confirmSave: '“{{name}}” şablonunun adını, açıklamasını ve görünürlüğünü kaydetmek istiyor musunuz? Yeni durum: {{visibility}}.', saved: '{{name}} şablonu kaydedildi.', stale: 'Şablon siz düzenlerken başka bir yönetici tarafından değiştirildi. Kaydetmeden önce güncel sürümü yenileyin.', authRequired: 'Bu görünüm için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', saveAuthRequired: 'Kaydetmek için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', saveError: 'Şablon kaydedilemedi. Bağlantınızı kontrol edip yeniden deneyin.',
      },
      operational: {
        payments: 'Ödemeler', audit: 'Denetim kayıtları', paymentsDescription: 'En son güncellenen ödeme kayıtları. Hesap ve davetiye bilgileri bu listede yer almaz.', auditDescription: 'En yeni yönetim olayları. Kayıtlar eklenmeye devam eder ve şu an için otomatik silinmez.', total: 'Toplam: {{count}}', loading: '{{title}} yükleniyor…', loadFailed: '{{title}} yüklenemedi', retry: 'Yeniden dene', emptyTitle: 'Henüz kayıt yok', paymentsEmpty: 'Ödeme kaydı oluştuğunda burada görünür.', auditEmpty: 'Yönetim olayı oluştuğunda burada görünür.', tableScroll: '{{title}} tablosu. Dar ekranda yatay kaydırılabilir.', pages: '{{title}} sayfaları', previous: 'Önceki', next: 'Sonraki', page: 'Sayfa {{current}} / {{total}}', paymentCaption: 'Ödeme kayıtları', auditCaption: 'Denetim kayıtları', reference: 'Referans', status: 'Durum', plan: 'Paket', amount: 'Tutar', created: 'Oluşturulma', updated: 'Son güncelleme', reversal: 'Ters kayıt', event: 'Olay', date: 'Tarih', actor: 'İşlemi yapan', subject: 'İlgili kayıt', authRequired: 'Bu görünüm için MFA doğrulaması tamamlanmış yönetici oturumu gerekiyor.', loadError: 'Kayıtlar şu anda alınamadı. Biraz sonra yeniden deneyin.', statusValues: { Pending: 'Bekliyor', Unknown: 'Belirsiz', Succeeded: 'Başarılı', Failed: 'Başarısız', Canceled: 'İptal edildi', Reversed: 'Ters kayıt', other: 'Diğer' }, reversalValues: { FullRefund: 'Tam iade', FinalLostChargeback: 'Sonuçlanmış kart itirazı', other: 'Ters kayıt' }, plans: { standard: 'Standard', premium: 'Premium', other: 'Diğer paket' },
      },
    },
  },
  en: {
    adminUi: {
      banned: {
        title: 'Banned accounts', description: 'Search banned account summaries by email prefix. Internal notes are not shown here.', total: 'Total: {{count}}', emailPrefix: 'Email prefix', search: 'Search', loading: 'Loading banned accounts…', loadFailed: 'Banned accounts could not be loaded', retry: 'Try again', emptyMatchTitle: 'No matching banned accounts', emptyTitle: 'No banned accounts', tryDifferentPrefix: 'Try a different email prefix.', emptyBody: 'Banned accounts appear in this list.', pages: 'Banned account pages', previous: 'Previous', next: 'Next', page: 'Page {{current}} / {{total}}', caption: 'Banned accounts', account: 'Account', email: 'Email', type: 'Type', created: 'Registered', bannedAt: 'Banned at', reason: 'Reason', action: 'Action', unnamedAccount: 'Unnamed account', noEmail: 'No email', unspecified: 'Not specified', unban: 'Lift ban', unbanning: 'Lifting ban…', unbanAria: 'Lift the ban for {{name}}', individual: 'Individual', organization: 'Organization', authRequired: 'An administrator session with completed MFA is required for this view.', loadError: 'Banned accounts are unavailable right now. Please try again shortly.', confirmUnban: 'Lift the ban for {{name}}? This will restore the account’s access.', unbanSuccess: 'The ban was lifted for {{name}}.', actionAuthRequired: 'An administrator session with completed MFA is required for this action.', unbanError: 'The ban could not be lifted. The account may have changed; refresh the list and try again.',
      },
      plans: {
        title: 'Plans and entitlements', description: 'Manage plan names, descriptions, prices, billing types and supported entitlement values.', loading: 'Loading plans…', loadFailed: 'Plans could not be loaded', loadError: 'The plan list is unavailable right now. Please try again shortly.', retry: 'Try again', emptyTitle: 'No plans to manage', emptyBody: 'Plan definitions will appear here when available.', planList: 'Plans to edit', planDetails: 'Plan details', revision: 'Revision {{revision}}', planName: 'Plan name', descriptionLabel: 'Description', optional: '(optional)', maxChars: 'Up to 2,000 characters.', amount: 'Plan amount ({{currency}})', priceHint: 'Up to 4 decimal places. A free plan must cost 0; one-time and monthly plans must cost more than 0. Currency is read-only. Price changes apply to new purchases only; existing publication grants and subscriptions keep their previous price.', billing: 'Billing type', free: 'Free', oneTime: 'One-time', periodMonthly: 'monthly', periodOneTime: 'one-time', periodFree: 'free', monthly: 'Monthly', freeMustBeZero: 'A free plan must cost zero. Set the amount to 0 or choose another billing type.', paidMustBePositive: 'Paid plans must cost more than zero. Enter a positive amount.', entitlements: 'Plan entitlements', entitlementHint: 'Numeric fields accept whole numbers. Supported limits are validated by the server; changing these values does not delete existing usage data.', missingEntitlement: 'Could not load data for {{name}}.', enabled: 'On', disabled: 'Off', currentRevision: 'Current plan revision', refreshConflict: 'Load the latest server values. Your local edits will be preserved until you do.', refresh: 'Load latest revision', saveChanges: 'Save changes', saving: 'Saving…', visible: 'visible in catalog', hidden: 'hidden from catalog', confirmSave: 'The “{{name}}” plan will change from {{oldPrice}} to {{newPrice}}. Price and billing changes apply only to new purchases; existing publication grants and subscriptions keep their current price. Lowering limits will not delete existing data. Continue?', saved: 'The {{name}} plan was saved.', stale: 'Another administrator changed this plan while you were editing it. Your local edits are preserved; load the latest revision before saving.', invalidServer: 'The server rejected the plan values or supported limits. Review the values and try again.', authRequired: 'An administrator session with completed MFA is required for this view.', saveAuthRequired: 'An administrator session with completed MFA is required to save.', saveError: 'The plan could not be saved. Check your connection and try again.',
        fields: { maxPublishDays: 'Maximum publication period (days)', maxActiveInvitations: 'Active invitations at a time', maxImages: 'Creator photo allowance', maxVideos: 'Creator video allowance', maxImageSizeMb: 'Creator photo size (MB)', maxVideoSizeMb: 'Creator video size (MB)', maxVideoDurationSeconds: 'Creator video duration (seconds)', maxGuestImages: 'Guest photo allowance', maxGuestVideos: 'Guest video allowance', maxGuestImageSizeMb: 'Guest photo size (MB)', maxGuestVideoSizeMb: 'Guest video size (MB)', maxGuestVideoDurationSeconds: 'Guest video duration (seconds)', maxRSVPResponses: 'RSVP responses per invitation', memoriesEnabled: 'Memories module', giftRegistryEnabled: 'Gift registry', premiumTemplatesEnabled: 'Premium templates' },
      },
      settings: {
        title: 'System settings', description: 'Only invitation and incomplete memory retention periods can be edited.', loading: 'Loading system settings…', loadFailed: 'Settings could not be loaded', loadError: 'System settings are unavailable right now. Please try again shortly.', retry: 'Try again', emptyTitle: 'No editable retention settings', emptyBody: 'Approved retention settings will appear here when provided by the API.', days: 'Period (days)', range: 'Whole days from 0 to 365. Server limit: {{minimum}}–{{maximum}} days.', currentValue: 'Current value for {{name}}', unsavedPreserved: 'Your unsaved value is preserved. Loading the latest server value will replace your edit.', refresh: 'Load latest value', saving: 'Saving…', save: 'Save change', revision: 'Revision {{revision}}', authRequired: 'An administrator session with completed MFA is required to view these settings.', refreshError: 'The latest setting could not be loaded. Check your connection and try again.', invalidDays: 'The retention period must be a whole number from 0 to 365.', confirmSave: 'Save {{name}} as {{value}} days? {{impact}}', saved: '{{name}} was saved. It will apply to new purchases and relevant new record operations.', conflict: '{{name}} was changed by another administrator while you were editing it. Your edit is preserved; load the latest value before saving.', saveAuthRequired: 'An administrator session with completed MFA is required to save.', saveError: 'The setting could not be saved. Check the value and try again.', settingTitles: { deletedInvitationRetentionDays: 'Deleted invitation retention period', abandonedMemoryRetentionDays: 'Incomplete memory retention period' }, settingEffects: { deletedInvitationRetentionDays: 'This change applies to invitations moved to trash from now on. Permanent deletion dates for existing invitations will not change.', abandonedMemoryRetentionDays: 'Expired abandoned memory and capability metadata records are cleaned up in limited batches. MediaAsset, PendingUpload, provider file bytes and guest allowance are retained until the invitation is permanently deleted.' },
      },
      templates: {
        title: 'Templates', description: 'Manage template names, optional descriptions and catalog visibility. Design and renderer details are maintained in code.', loading: 'Loading templates…', loadFailed: 'Templates could not be loaded', loadError: 'The template list is unavailable right now. Please try again shortly.', retry: 'Try again', emptyTitle: 'No templates to manage', emptyBody: 'Template definitions will appear here when available.', listLabel: 'Templates to edit', visible: 'Visible', hidden: 'Hidden', details: 'Template details', revision: 'Revision {{revision}}', name: 'Name', descriptionLabel: 'Description', optional: '(optional)', maxChars: 'Up to 2,000 characters.', showInCatalog: 'Show in catalog', hiddenHint: 'Hidden templates are removed from new selections; existing drafts and published invitations are not affected.', currentRevision: 'Current template revision', refreshConflict: 'Load the latest server values to refresh these changes.', refresh: 'Load latest revision', saveChanges: 'Save changes', saving: 'Saving…', confirmSave: 'Save the name, description and visibility of template “{{name}}”? New status: {{visibility}}.', saved: 'Template {{name}} was saved.', stale: 'Another administrator changed this template while you were editing it. Load the latest revision before saving.', authRequired: 'An administrator session with completed MFA is required for this view.', saveAuthRequired: 'An administrator session with completed MFA is required to save.', saveError: 'The template could not be saved. Check your connection and try again.',
      },
      operational: {
        payments: 'Payments', audit: 'Audit log', paymentsDescription: 'Most recently updated payment records. Account and invitation details are not included in this list.', auditDescription: 'Most recent administration events. Records continue to accumulate and are not automatically deleted at this time.', total: 'Total: {{count}}', loading: 'Loading {{title}}…', loadFailed: '{{title}} could not be loaded', retry: 'Try again', emptyTitle: 'No records yet', paymentsEmpty: 'Payment records will appear here when created.', auditEmpty: 'Administration events will appear here when created.', tableScroll: '{{title}} table. Scroll horizontally on narrow screens.', pages: '{{title}} pages', previous: 'Previous', next: 'Next', page: 'Page {{current}} / {{total}}', paymentCaption: 'Payment records', auditCaption: 'Audit log', reference: 'Reference', status: 'Status', plan: 'Plan', amount: 'Amount', created: 'Created', updated: 'Last updated', reversal: 'Reversal', event: 'Event', date: 'Date', actor: 'Performed by', subject: 'Related record', authRequired: 'An administrator session with completed MFA is required for this view.', loadError: 'Records are unavailable right now. Please try again shortly.', statusValues: { Pending: 'Pending', Unknown: 'Unknown', Succeeded: 'Succeeded', Failed: 'Failed', Canceled: 'Canceled', Reversed: 'Reversed', other: 'Other' }, reversalValues: { FullRefund: 'Full refund', FinalLostChargeback: 'Finalized chargeback', other: 'Reversal' }, plans: { standard: 'Standard', premium: 'Premium', other: 'Other plan' },
      },
    },
  },
} as const
